### ISSUE TITLE
ark模式下启动有一定概率NoClassDefFoundError

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-tracer#431]
sofaboot 版本 3.4.5

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.alipay.common.tracer.core.appender.self.SelfLog
	at com.alipay.common.tracer.core.appender.TracerLogRootDaemon.<clinit>(TracerLogRootDaemon.java:86)
	at com.alipay.common.tracer.core.appender.file.AbstractRollingFileAppender.<init>(AbstractRollingFileAppender.java:66)
	at com.alipay.common.tracer.core.appender.file.TimedRollingFileAppender.<init>(TimedRollingFileAppender.java:115)
	at com.alipay.common.tracer.core.appender.file.TimedRollingFileAppender.<init>(TimedRollingFileAppender.java:91)
	at com.alipay.common.tracer.core.appender.info.StaticInfoLog.logStaticInfo(StaticInfoLog.java:39)
	at com.alipay.common.tracer.core.configuration.SofaTracerConfiguration.<clinit>(SofaTracerConfiguration.java:137)
	at com.alipay.sofa.tracer.boot.listener.SofaTracerConfigurationListener.onApplicationEvent(SofaTracerConfigurationListener.java:59)
	at com.alipay.sofa.tracer.boot.listener.SofaTracerConfigurationListener.onApplicationEvent(SofaTracerConfigurationListener.java:41)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
```

**Comment by leizhiyuan** [comment]
关闭
