### ISSUE TITLE
dubbo 2.7 使用问题

### ISSUE THREAD

**Issue by vacuityv** [sofastack/sofa-tracer#511]
### Your question

目前项目中用的dubbo的2.7.15，我引入了sofa-tracer-dubbo-common-plugin的3.1.0，为什么他自动用了这个common里面2.6的版本：com.alipay.sofa.tracer.plugins.dubbo26x，导致项目报错，我在META-INF手动写了dubboSofaTracerFilter=com.alipay.sofa.tracer.plugins.dubbo27x.DubboSofaTracerFilter依然没用，有人知道原因吗

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by vacuityv** [comment]
看到了错误点：
at com.alibaba.dubbo.rpc.Filter.invoke(Filter.java:29) ~[dubbo-2.7.15.jar:2.7.15]
at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
有人知道为什么这里会突然使用alibaba包名下的Filter吗，我看FilterNode里面import的是apache的啊：
<img width="560" alt="image" src="https://github.com/sofastack/sofa-tracer/assets/13598237/dc9ea6de-9792-4639-9089-785ea57de185">
